services:

  rabbitmq:
    image: rabbitmq:4.2-management
    container_name: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: celery
      RABBITMQ_DEFAULT_PASS: celery

    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 10


  api:
    build: .
    container_name: fastapi

    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    environment:
      CELERY_BROKER_URL: amqp://celery:celery@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://

    depends_on:
      rabbitmq:
        condition: service_healthy


  worker:
    build: .
    container_name: celery-worker

    command: >
      celery
      -A celery_app.celery
      worker
      --loglevel=info

    volumes:
      - .:/app

    environment:
      CELERY_BROKER_URL: amqp://celery:celery@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://

    depends_on:
      rabbitmq:
        condition: service_healthy
